# -*- coding: utf-8 -*-
"""project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nHAE9yOa9A6BtEx3kfeU3YL0iP0B5FFf
"""

# packages
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import statsmodels.api as sm
from sklearn.model_selection import train_test_split
from statsmodels.stats.outliers_influence import variance_inflation_factor
from statsmodels.tools.tools import add_constant
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

"""# **2. data preprocessing**"""

file_path = 'DelayData.csv'
flight_data = pd.read_csv(file_path)
# Drop null values & duplicated columns
flight_data = flight_data.dropna().drop(columns=['arrdelay', 'tailnum', 'origin', 'dest', 'origincityname', 'originstate', 'windspeedsquare',
                                                 'temp_ninfty_n10', 'temp_n10_0', 'temp_0_10', 'temp_10_20', 'temp_20_30', 'temp_30_40', 'temp_40_infty',
                                                 'nonhubairportorigin', 'nonhubairportdest', 'nonhubairlineorigin', 'nonhubairlinedest'])
#Target Encoding Categorical variables
carrier_encoded = flight_data.groupby('uniquecarrier')['depdelay'].mean()
flight_data['uniquecarrier'] = flight_data['uniquecarrier'].map(carrier_encoded)
orig_encoded = flight_data.groupby('originairportid')['depdelay'].mean()
flight_data['originairportid'] = flight_data['originairportid'].map(orig_encoded)
orig_encoded = flight_data.groupby('originairportid')['depdelay'].mean()
flight_data['originairportid'] = flight_data['originairportid'].map(orig_encoded)
flight_data['scheduleddepartdatetime'] = pd.to_datetime(flight_data['scheduleddepartdatetime'], format='%d-%b-%Y %H:%M:%S', errors='coerce')
flight_data['minute'] = flight_data['scheduleddepartdatetime'].dt.minute
flight_data = flight_data.drop(columns=['scheduleddepartdatetime'])
# Remove outliers
Q1 = flight_data['depdelay'].quantile(0.25)
Q3 = flight_data['depdelay'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 10 * IQR
upper_bound = Q3 + 20 * IQR
filtered_data = flight_data[(flight_data['depdelay'] >= lower_bound) & (flight_data['depdelay'] <= upper_bound)]
print(f"Original size: {len(flight_data)}, After removing outliers: {len(filtered_data)}")
# Plot distribution
plt.figure(figsize=(10, 6))
sns.histplot(filtered_data['depdelay'], bins=50, kde=True, color='blue')
plt.title('Distribution of Departure Delays (depdelay) - Outliers Removed', fontsize=16)
plt.xlabel('Departure Delay (minutes)', fontsize=12)
plt.ylabel('Frequency', fontsize=12)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

# Check correlation(all ｜c｜< 0.8)
correlation_matrix = filtered_data.corr()
plt.figure(figsize=(15, 10))
sns.heatmap(correlation_matrix, annot=True, fmt='.2f', cmap='coolwarm')
plt.title('Correlation Matrix')
plt.show()

# Check Multicollinearity(VIF < 5)
X = filtered_data
X = add_constant(X)
vif_data = pd.DataFrame()
vif_data['Feature'] = X.columns
vif_data['VIF'] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
print(vif_data)

# Train/test split
X = filtered_data.drop(columns=['depdelay'])
y = filtered_data['depdelay']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train = sm.add_constant(X_train)
X_test = sm.add_constant(X_test)
y_train_binary = (y_train > 0).astype(int)
y_test_binary = (y_test > 0).astype(int)

"""# **3. setup classification models**"""

# Baseline
baseline_1_acc = (y_test_binary == 0).sum() / len(y_test_binary)
print(f'Baseline Test Accuracy: {baseline_1_acc:.4f}')

"""# **Logistic**"""

# Logistic before PCA
model = sm.Logit(y_train_binary, X_train)
result = model.fit()
print(result.summary())
y_test_pred_prob = result.predict(X_test)
y_pred_logistic = (y_test_pred_prob > 0.5).astype(int)
accuracy = accuracy_score(y_test_binary, y_pred_logistic)
print(f"Logistic Test Accuracy: {accuracy:.4f}")
print("Logistic Model Confusion Matrix:")
print(confusion_matrix(y_test_binary, y_pred_logistic))

"""# **CART**"""

# CART

from sklearn.tree import DecisionTreeClassifier
import matplotlib.pyplot as plt
from sklearn.tree import plot_tree
import numpy as np
from sklearn.model_selection import GridSearchCV

cart = DecisionTreeClassifier(random_state = 2024,
    max_depth=3,
    min_samples_split=20,
    min_samples_leaf=10)

param_grid = {'ccp_alpha': np.linspace(0, 0.1, 20)}

cart_gridscv = GridSearchCV(estimator = cart, param_grid = param_grid, cv=5, scoring='accuracy', verbose=1)
cart_gridscv.fit(X_train, y_train_binary)
best_params = cart_gridscv.best_params_
best_cart = cart_gridscv.best_estimator_
y_pred_cart = best_cart.predict(X_test)

accuracy_cart = accuracy_score(y_test_binary, y_pred_cart)
print("CART Model Accuracy:", accuracy)
print("CART Model Confusion Matrix:")
print(confusion_matrix(y_test_binary, y_pred_cart))

# plot CART decision tree
plt.figure(figsize=(12, 8))
plot_tree(best_cart, filled=True, feature_names=X_test.columns, fontsize=10)
plt.title('Decision Tree for Flight Delay Prediction')
plt.show()

"""# **random forest**"""

# Random Forest

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

rf = RandomForestClassifier(random_state=2024,
                            min_samples_leaf=5)

grid_values = {'max_features': [1, 2, 3],
               'min_samples_leaf': [5],
               'n_estimators': [10],
               'random_state': [2024]}
rf_cv = GridSearchCV(estimator = rf, param_grid = grid_values, cv=5, scoring='accuracy', verbose=1)

rf_cv.fit(X_train, y_train_binary)
best_params_rf = rf_cv.best_params_

best_rf = rf_cv.best_estimator_
y_pred_rf = best_rf.predict(X_test)

accuracy_rf = accuracy_score(y_test_binary, y_pred_rf)
print("Random Forest Model Accuracy:", accuracy_rf)
print("Random Forest Model Confusion Matrix:")
print(confusion_matrix(y_test_binary, y_pred_rf))

"""# **Gradient descent**"""

# gradient descent
from sklearn.ensemble import GradientBoostingClassifier

gb = GradientBoostingClassifier(n_estimators=300, max_leaf_nodes=15, random_state=2024)

gb.fit(X_train, y_train_binary)

y_pred_gd = gb.predict(X_test)

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
cm = confusion_matrix(y_test_binary, y_pred_gd)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=gb.classes_)
disp.plot(cmap='Blues')
plt.title("Confusion Matrix for gradient boosting Classifier")
plt.show()

accuracy = accuracy_score(y_test_binary, y_pred_gd)
print(f"Accuracy: {accuracy:.4f}")

import xgboost as xgb
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import pandas as pd
import matplotlib.pyplot as plt

#xgboost before PCA
# Convert data to DMatrix
dtrain = xgb.DMatrix(X_train, label=y_train_binary)
dtest = xgb.DMatrix(X_test, label=y_test_binary)

# Define XGBoost parameters
params = {
    "objective": "binary:logistic",  # Binary classification
    "eval_metric": "logloss",       # Evaluation metric
    "eta": 0.1,                     # Learning rate
    "max_depth": 6,                 # Depth of tree
    "seed": 999
}

# Train the model
num_boost_round = 100
model = xgb.train(params, dtrain, num_boost_round)

# Make predictions
y_pred_prob = model.predict(dtest)  # Probabilities
y_pred = (y_pred_prob > 0.5).astype(int)  # Convert to binary predictions

# Evaluate the model
accuracy = accuracy_score(y_test_binary, y_pred)
print("Accuracy:", accuracy)
print("\nClassification Report:")
print(classification_report(y_test_binary, y_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test_binary, y_pred))

# Feature importance
importance = model.get_score(importance_type='weight')
importance_df = pd.DataFrame(
    list(importance.items()), columns=['Feature', 'Importance']
).sort_values(by="Importance", ascending=False)

print("\nFeature Importance:")
print(importance_df)

# Plot feature importance
plt.figure(figsize=(10, 6))
xgb.plot_importance(model, importance_type='weight')
plt.title("Feature Importance")
plt.show()

# Calculate the percentage of predicted delays
total_flights = len(y_pred)
delayed_flights = sum(y_pred)
percentage_delayed = (delayed_flights / total_flights) * 100


print(f"Number of predictions made: {total_flights}")

"""# **Bagging**"""

from scipy.stats import mode
import numpy as np
file_path = 'Predicted_Binary_Outcomes.csv'
y_pred_xgboost = pd.read_csv(file_path)['Prediction'].values
predictions = np.array([y_pred_rf, y_pred_xgboost, y_pred_gd]).T
print(predictions.shape)
# Apply majority voting
y_pred_bagging = mode(predictions, axis=1).mode
y_pred_bagging = y_pred_bagging.flatten()
# Print the final bagged prediction
print("Bagged Prediction accuracy:", accuracy_score(y_test_binary, y_pred_bagging))
cm = confusion_matrix(y_test_binary, y_pred_bagging)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=gb.classes_)
disp.plot(cmap='Blues')
plt.title("Confusion Matrix for Bagging Classifier")
plt.show()

"""# **5. PCA**"""

# Standardize the data
import numpy as np
scaler = StandardScaler()
data_scaled = scaler.fit_transform(X)

# Apply PCA with all components
pca_full = PCA()
pca_full.fit(data_scaled)

explained_variance_ratios = pca_full.explained_variance_ratio_
cumulative_variance = np.cumsum(explained_variance_ratios)

# Plot cumulative explained variance
plt.figure(figsize=(8, 5))
plt.plot(range(1, len(cumulative_variance)+1), cumulative_variance, marker='o', linestyle='--')
plt.title('Cumulative Explained Variance by PCA Components')
plt.xlabel('Number of Components')
plt.ylabel('Cumulative Explained Variance')
plt.grid()
plt.show()

n_optimal_components = np.argmax(cumulative_variance >= 0.90) + 1
pca_optimal = PCA(n_components=n_optimal_components)
principal_components = pca_optimal.fit_transform(data_scaled)

print(f"Optimal number of components: {n_optimal_components}")
print(f"Explained variance by optimal PCA: {np.sum(pca_optimal.explained_variance_ratio_)}")

import numpy as np

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

pca = PCA(n_components=20)
X_train_pca = pca.fit_transform(X_train_scaled)
X_test_pca = pca.transform(X_test_scaled)

explained_variance = pca.explained_variance_ratio_
cumulative_variance = np.cumsum(explained_variance)

# Print results
print("\nExplained Variance Ratio (Training Set):")
print(explained_variance)

print("\nCumulative Explained Variance (Training Set):")
print(cumulative_variance)

print("\nShape of X_train_pca:", X_train_pca.shape)
print("Shape of X_test_pca:", X_test_pca.shape)
# principal_components = pca.fit_transform(data_scaled)
# X_pca = pd.DataFrame(data=principal_components)
# X_pca.columns = X_pca.columns.astype(str)
# explained_variance = pca.explained_variance_ratio_
# print("\nExplained Variance Ratio:")
# print(explained_variance)
# cumulative_variance = np.sum(explained_variance)
# print("\nExplained Variance in total:",cumulative_variance)

"""# **classification models After PCA**"""

# Logistic after PCA
model = sm.Logit(y_train_binary, X_train_pca)
result = model.fit()
y_test_pred_prob = result.predict(X_test_pca)
y_test_pred = (y_test_pred_prob > 0.5).astype(int)
accuracy = accuracy_score(y_test_binary, y_test_pred)
print(f"Logistic Test Accuracy: {accuracy:.2f}")

#xgboost after pca
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
xgb_model = XGBClassifier(
    n_estimators=100,      # Number of trees
    max_depth=6,           # Maximum depth of a tree
    learning_rate=0.1,     # Step size shrinkage
    subsample=0.8,         # Fraction of samples used for training each tree
    colsample_bytree=0.8,  # Fraction of features used for training each tree
    random_state=42        # For reproducibility
)
xgb_model.fit(X_train_pca, y_train_binary)
y_pred_xgb = xgb_model.predict(X_test_pca)

# Accuracy
accuracy = accuracy_score(y_test_binary, y_pred_xgb)
print(f"Accuracy: {accuracy:.2f}")

# Classification Report
print("Classification Report:")
print(classification_report(y_test_binary, y_pred_xgb))

# Confusion Matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test_binary, y_pred_xgb))

# gradient descent
from sklearn.ensemble import GradientBoostingClassifier

gb = GradientBoostingClassifier(n_estimators=300, max_leaf_nodes=15, random_state=2024)

gb.fit(X_train_pca, y_train_binary)

y_pred_gd = gb.predict(X_test_pca)

cm = confusion_matrix(y_test_binary, y_pred_gd)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=gb.classes_)
disp.plot(cmap='Blues')
plt.title("Confusion Matrix for gradient boosting Classifier after PCA")
plt.show()

accuracy = accuracy_score(y_test_binary, y_pred_gd)
print(f"Accuracy: {accuracy:.4f}")